"""Prepare the dashboard for publishing as a hosted page.

The hosting platform wraps a published page in its own <!doctype>/<html>/<head>/<body>
skeleton, so this writes dashboard/artifact.html: the same page with those wrapper tags
removed (title, fonts, stylesheet and scripts kept, in order). The CSS, JS and data files are
published alongside it unchanged, so the hosted page shows exactly the validated data.

Run:  python -m src.reporting.publish_dashboard
"""
import re

from src.config import project_path

SRC = project_path("dashboard/index.html")
OUT = project_path("dashboard/artifact.html")
FILES = ["css/dashboard.css", "js/model.js", "js/charts.js", "js/app.js", "data/dashboard_data.js"]


def build():
    html = SRC.read_text(encoding="utf-8")
    head = re.search(r"<head>(.*?)</head>", html, re.S).group(1)
    body = re.search(r"<body>(.*?)</body>", html, re.S).group(1)
    head = re.sub(r'\s*<meta (charset|name="viewport")[^>]*>', "", head)  # the host supplies these
    out = "<!-- Generated by src/reporting/publish_dashboard.py from dashboard/index.html. Do not edit. -->\n" + head.strip() + "\n" + body.strip() + "\n"
    OUT.write_text(out, encoding="utf-8", newline="\n")
    return OUT


if __name__ == "__main__":
    print(f"Wrote {build()}")
